### ISSUE TITLE
Voltage alarm not correct and min/max display 

### ISSUE THREAD

**Issue by rizenfpv** [iNavFlight/LuaTelemetry#462]
RM TX16S (OpenTX 2.3.11) (Lua 1.7.4)

Ok so i have two questions. 

First one:

Whenever i arm my plane the battery voltage alarm goes off. Also in the Lua widget the almost full battery (2s1p 18650 li-ion) is only displayed with half of the voltage bar missing. Battery voltage is right though, but i want the alarm to go off when theres about 6V left in the battery.

Second one: 

When i give full up or down elevator the widget goes into min/max mode. Can i change that?

![20210508_211223.jpg](https://user-images.githubusercontent.com/83215820/117550749-419bed00-b042-11eb-8f01-af54e84d3b8e.jpg)

**Comment by teckel12** [comment]
First the easy one, full up or down elevator the widget goes into min/max mode.  This happens when you're not flying (not armed) to show either the last value or the min/max.

As far as the battery warning, are you resetting the flight?

https://github.com/teckel12/LuaTelemetry/wiki/Tips-&-Common-Problems#tips

> * Between flights (before armed), long-press Enter/dial and select `Reset telemetry` to reset telemetry values

What kind of battery are you using?  7.6v would assume to be a 2S lipo at 3.8v per cell (with 3.5v considered low).  If you're using a different battery chemistry, you're going to need to configure the setting accordingly.

https://github.com/teckel12/LuaTelemetry/wiki/Configuration-Settings

> Cell Low - Cell voltage for low battery warning (default: 3.5V) [help]
> Cell Critical - Cell voltage for battery critical warning (default: 3.4V) [help]
> Cell Calculation - Voltage to calculate cell count, 4.3V for LiPo, 4.4V for LiHV (default: 4.3V)

More battery information:

https://github.com/teckel12/LuaTelemetry/wiki/Suggested-Battery-Settings

Let me know if you're already read the documentation and still having a problem and how it could be modified to be more clear.
